### ISSUE TITLE
好像找不到ffmpeg

### ISSUE THREAD

**Issue by MomentDerek** [SigureMo/bilili-dl#2]
![image](https://user-images.githubusercontent.com/40252940/70995183-e8f54880-210a-11ea-93ef-32ce61424137.png)
![image](https://user-images.githubusercontent.com/40252940/70995207-f7436480-210a-11ea-8037-d4ff77d98990.png)

**Comment by SigureMo** [comment]
这个问题我最近也遇到了，这个问题建议直接将 `ffmpeg` 添加到环境变量，之后我可能仅支持环境变量的方式

**Comment by MomentDerek** [comment]
问题解决了
